// <auto-generated />
using APIMMwithoutJunctionModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIMMwithoutJunctionModel.Migrations
{
    [DbContext(typeof(DocPatientContext))]
    partial class DocPatientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIMMwithoutJunctionModel.Models.Doctor", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocId"));

                    b.Property<string>("DocName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DocId = 1,
                            DocName = "Prem",
                            Specialization = "Cardio"
                        });
                });

            modelBuilder.Entity("APIMMwithoutJunctionModel.Models.Patient", b =>
                {
                    b.Property<int>("PatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatId"));

                    b.Property<string>("PatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatId = 11,
                            PatName = "Liya"
                        });
                });

            modelBuilder.Entity("APIMMwithoutJunctionModel.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<int>("DoctorsDocId")
                        .HasColumnType("int");

                    b.Property<int>("PatientsPatId")
                        .HasColumnType("int");

                    b.HasKey("DoctorsDocId", "PatientsPatId");

                    b.HasIndex("PatientsPatId");

                    b.ToTable("DocPatient", (string)null);
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("APIMMwithoutJunctionModel.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMMwithoutJunctionModel.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsPatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
